context:
  version: "2.52.2"

package:
  name: spider_cli
  version: ${{ version }}

source:
  url: https://github.com/spider-rs/spider/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 130a9d6040a05a3c4d219fcd296f7f20ba6f7c90a8e18914b7d0f647db7908fa

build:
  number: 0
  script:
    env:
      AWS_LC_SYS_CMAKE_BUILDER: ${{ "1" if host_platform == "win-arm64" else "0" }} # force CMake builder for `aws-lc-sys` native C/C++ code on `win-arm64`
      CARGO_PROFILE_RELEASE_LTO: fat
      CARGO_PROFILE_RELEASE_STRIP: symbols
      # instruct `cc` crate to use clang-cl natively to compile build-time tools intended to be run on the host when cross-compiling from `win_64`
      AR_x86_64_pc_windows_msvc: llvm-lib
      CC_x86_64_pc_windows_msvc: clang-cl
      CXX_x86_64_pc_windows_msvc: clang-cl
    content:
      - cd spider_cli
      - if: unix
        then:
          - cargo auditable install --path=. --root="$PREFIX" --no-track --locked --bins
      - if: win
        then:
          - cargo auditable install --path=. --root="%LIBRARY_PREFIX%" --no-track --locked --bins
      - cargo-bundle-licenses --format=yaml --output=../THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-auditable
    - cargo-bundle-licenses
    - if: unix
      then: pkg-config
    - if: win
      then: cmake
  host:
    - if: linux
      then: openssl

tests:
  - script:
      - spider --help
      - spider --version
  - package_contents:
      bin:
        - spider
      strict: true

about:
  summary: spider (web crawler) CLI for high-performance website scraping.
  description: |
    A fast command-line spider (web crawler) written in Rust for high-performance website scraping. Optionally allows to provide an API key for spider.cloud to
    use their hosted services.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://spider.cloud/
  documentation: https://github.com/spider-rs/spider/tree/main/spider_cli
  repository: https://github.com/spider-rs/spider

extra:
  recipe-maintainers:
    - salim-b
