context:
  version: "2.52.2"

package:
  name: spider_cli
  version: ${{ version }}

source:
  url: https://github.com/spider-rs/spider/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 130a9d6040a05a3c4d219fcd296f7f20ba6f7c90a8e18914b7d0f647db7908fa

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - cd spider_cli
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
      - if: win
        then:
          - cargo auditable install --locked --no-track --bins --root %LIBRARY_PREFIX% --path .
      - cargo-bundle-licenses --format yaml --output ../THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - if: unix
      then: pkg-config
  host:
    - openssl

tests:
  - script:
      - spider --help
      - spider --version
  - package_contents:
      bin:
        - spider
      strict: true

about:
  summary: spider (web crawler) CLI for high-performance website scraping.
  description: |
    A fast command-line spider (web crawler) written in Rust for high-performance website scraping. Optionally allows to provide an API key for spider.cloud to
    use their hosted services.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://spider.cloud/
  documentation: https://github.com/spider-rs/spider/tree/main/spider_cli
  repository: https://github.com/spider-rs/spider

extra:
  recipe-maintainers:
    - salim-b
